# Generated by Django 5.0 on 2025-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='pay_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
