# Generated by Django 5.2.6 on 2025-09-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text="Your professional headline (e.g., 'Software Engineer with 3 years experience')", max_length=200)),
                ('skills', models.TextField(blank=True, help_text='List your skills separated by commas or new lines')),
                ('education', models.TextField(blank=True, help_text='Your educational background')),
                ('work_experience', models.TextField(blank=True, help_text='Your work experience and achievements')),
                ('links', models.TextField(blank=True, help_text='Professional links (LinkedIn, GitHub, Portfolio, etc.)')),
                ('show_headline', models.BooleanField(default=True, help_text='Show headline to recruiters')),
                ('show_skills', models.BooleanField(default=True, help_text='Show skills to recruiters')),
                ('show_education', models.BooleanField(default=True, help_text='Show education to recruiters')),
                ('show_work_experience', models.BooleanField(default=True, help_text='Show work experience to recruiters')),
                ('show_links', models.BooleanField(default=True, help_text='Show professional links to recruiters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
