# Generated by Django 5.0 on 2025-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text="Your current location (e.g., 'New York, NY' or 'San Francisco, CA')", max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(blank=True, help_text='Your projects with descriptions, technologies used, etc.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_location',
            field=models.BooleanField(default=True, help_text='Show location to recruiters'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_projects',
            field=models.BooleanField(default=True, help_text='Show projects to recruiters'),
        ),
    ]
