# Generated by Django 5.2.7 on 2025-10-19 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('profiles', '0002_profile_location_profile_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=200)),
                ('search_query', models.CharField(blank=True, help_text='General search query', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Location filter', max_length=200)),
                ('skills', models.CharField(blank=True, help_text='Skills filter (comma-separated)', max_length=500)),
                ('projects', models.CharField(blank=True, help_text='Projects filter', max_length=500)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Get notified when new candidates match this search')),
                ('last_notified', models.DateTimeField(blank=True, help_text='Last time notifications were sent for this search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='authentication.recruiterprofile')),
            ],
            options={
                'verbose_name_plural': 'Saved searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_notifications', to=settings.AUTH_USER_MODEL)),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='profiles.savedsearch')),
            ],
            options={
                'ordering': ['-notified_at'],
                'unique_together': {('saved_search', 'candidate')},
            },
        ),
    ]
