# Generated by Django 5.0 on 2025-11-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_savedsearch_searchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Optional: precise latitude for your location', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Optional: precise longitude for your location', null=True),
        ),
    ]
